#!/usr/bin/env bash

export COLOR_RESET="\e[0m"

export COLOR_FOREGROUND_BLACK="\e[30m"
export COLOR_FOREGROUND_RED="\e[31m"
export COLOR_FOREGROUND_GREEN="\e[32m"
export COLOR_FOREGROUND_YELLOW="\e[33m"
export COLOR_FOREGROUND_BLUE="\e[34m"
export COLOR_FOREGROUND_MAGENTA="\e[35m"
export COLOR_FOREGROUND_CYAN="\e[36m"
export COLOR_FOREGROUND_WHITE="\e[37m"

export COLOR_BACKGROUND_BLACK="\e[40m"
export COLOR_BACKGROUND_RED="\e[41m"
export COLOR_BACKGROUND_GREEN="\e[42m"
export COLOR_BACKGROUND_YELLOW="\e[43m"
export COLOR_BACKGROUND_BLUE="\e[44m"
export COLOR_BACKGROUND_MAGENTA="\e[45m"
export COLOR_BACKGROUND_CYAN="\e[46m"
export COLOR_BACKGROUND_WHITE="\e[46m"

export COLOR_BACKGROUND_BRIGHT_BLACK="\e[40;1m"
export COLOR_BACKGROUND_BRIGHT_RED="\e[41;1m"
export COLOR_BACKGROUND_BRIGHT_GREEN="\e[42;1m"
export COLOR_BACKGROUND_BRIGHT_YELLOW="\e[43;1m"
export COLOR_BACKGROUND_BRIGHT_BLUE="\e[44;1m"
export COLOR_BACKGROUND_BRIGHT_MAGENTA="\e[45;1m"
export COLOR_BACKGROUND_BRIGHT_CYAN="\e[46;1m"
export COLOR_BACKGROUND_BRIGHT_WHITE="\e[46;1m"

function supports256Color {
  grep -c 256 <<<"$TERM"
}

if [[ $(supports256Color) -eq 1 ]]; then
  export COLOR_SUPPORTS_256=""
fi
